### ISSUE TITLE
Добавить к репозиторию файлы из cocalc  

### ISSUE THREAD

**Issue by Toundra** [QuadraT2x2/game#1]
с классами character, hero, monster_creator, property, potion, inventory(.py)

Задача на 5-ку - сделать это пулл-реквестом

**Comment by Toundra** [comment]
@QuadraT2x2 
Пожалуйста, добавь все классы, а не только те, что тут написаны.

**Comment by Toundra** [comment]
@QuadraT2x2 исправил в https://github.com/QuadraT2x2/game/commit/6036bf8b2dca2a8f9649acb658de21ebf500e5d5

**Comment by QuadraT2x2** [comment]
херакс 36d9d3bb9ac1a8a2b2f5a8013628e3bcfbbf0ead
