### ISSUE TITLE
Сделать отдельный .py файл для тестов

### ISSUE THREAD

**Issue by Toundra** [QuadraT2x2/game#2]
Инициализируется 3 героя, 5 базовых монстров, 25 финальных монстров с property

**Comment by Toundra** [comment]
я начал в f7bc6a8996ead8cf45bbc3b9fe9c556c1d9a8fbe - остальное на тебе @QuadraT2x2

**Comment by QuadraT2x2** [comment]
сделал 5b4391772ba875e03fa01c436b8cdcb4f8a76201

**Comment by QuadraT2x2** [comment]
героев раскоментил и добавил списки 5 обычных мобов и 25 с проп, сунул 3 пота вору. после драки с первым обычным мобом выпил пот e9634a7f9a98060846a3c649f37f337a59819544

**Comment by Toundra** [comment]
Смотрю 5b43917 
1. Монстрам предлагаю сделать имена с большой буквы.
2. monster_creater создаёт монстров без проперти с названием всё равно с пробелом в названии - надо исправить.
![изображение](https://user-images.githubusercontent.com/44191493/96637081-dfd69880-1326-11eb-9eef-122c46e4c4ac.png)

**Comment by Toundra** [comment]
[thief.inventory.add_item(potion) for i in range(3)] - не нравится.


у нас так написан inventory, что мы можем добавлять туда только что-то императивно, а не декларативно.
типа 
машина = корпус.
корпус.добавь_колесо(новое колесо())
корпус.добавь_колесо(новое колесо())
корпус.добавь_колесо(новое колесо())
корпус.добавь_колесо(новое колесо())

можно заменить на 
машина = корпус
for i in range(4):
    корпус.добавь_колесо(новое колесо())

можно заменить на 
машина = корпус
корпус.добавить_колёса([новое колесо() for i in range(4)])

**Comment by QuadraT2x2** [comment]
херакс 36d9d3bb9ac1a8a2b2f5a8013628e3bcfbbf0ead
