### ISSUE TITLE
рефакторинг под игру

### ISSUE THREAD

**Issue by Toundra** [QuadraT2x2/game#4]
2. width, height, rows, columns, margin - в отдельный файл screen_confg.py
3. draw_picture - перенести в graphics_utils

1. у каждого монстра своя картинка - скачать картинки для текущих монстров
2. статично прорисовать всех монстров на нулевом ряду (это означает, что движуха с аяёй работает с первого ряда и дальше)

**Comment by Toundra** [comment]
for row in range(1, rows): 
для того, чтобы первый ряд не трогать в рисовании колонок и рядов

**Comment by QuadraT2x2** [comment]
сделать красиво - "статично прорисовать всех монстров на нулевом ряду"

**Comment by Toundra** [comment]
непонятно про "сделать красиво", закрываю
