### ISSUE TITLE
Изменения в интерфейсе

### ISSUE THREAD

**Issue by Toundra** [QuadraT2x2/game#7]
В правой части экрана, там, где сейчас тест, необходимо собрать интерфейс:
стрелочки + место под большой портрет (220*220).

**Comment by Toundra** [comment]
![изображение](https://user-images.githubusercontent.com/44191493/99498518-a4aca100-2988-11eb-94ca-8ecf9fe69b13.png)

**Comment by Toundra** [comment]
в центре пустая кнопка.

**Comment by QuadraT2x2** [comment]
доделал 3d5d10787699046431d57ff012ec7c0e043b52ea

**Comment by Toundra** [comment]
доделал - закрой @QuadraT2x2
